# Generated by Django 4.2.20 on 2025-04-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='event name')),
                ('date', models.DateTimeField(verbose_name='event date')),
                ('venue', models.CharField(max_length=100, verbose_name='event venue')),
                ('manager', models.CharField(max_length=100, verbose_name='event manager name')),
                ('description', models.TextField(blank=True, verbose_name='game event description')),
            ],
        ),
    ]
