# Generated by Django 4.2.20 on 2025-04-06 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfUsers_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='user email')),
            ],
        ),
        migrations.CreateModel(
            name='Venue_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='venue name')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('pin_code', models.CharField(max_length=15, verbose_name='pin code')),
                ('phone', models.CharField(max_length=15, verbose_name='phone number')),
                ('web', models.URLField(verbose_name='Website Address')),
                ('email_address', models.EmailField(max_length=254, verbose_name='EmailField')),
            ],
        ),
        migrations.AddField(
            model_name='event_db',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='events.turfusers_db'),
        ),
        migrations.AlterField(
            model_name='event_db',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.venue_db'),
        ),
    ]
