# Generated by Django 4.2.20 on 2025-04-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_turfusers_db_venue_db_event_db_attendees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_db',
            name='venue',
        ),
    ]
