# Generated by Django 4.2.20 on 2025-04-06 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_db_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_db',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.venue_db'),
        ),
    ]
