# Generated by Django 4.2.20 on 2025-04-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_db_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue_db',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='EmailField'),
        ),
        migrations.AlterField(
            model_name='venue_db',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='venue_db',
            name='web',
            field=models.URLField(blank=True, verbose_name='Website Address'),
        ),
    ]
