# Generated by Django 4.2.20 on 2025-04-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_venue_db_email_address_alter_venue_db_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue_db',
            name='pin_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='pin code'),
        ),
    ]
