# Generated by Django 4.2.20 on 2025-04-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_db_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue_db',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='owner id'),
        ),
        migrations.AlterField(
            model_name='turfusers_db',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='user email'),
        ),
    ]
