# Generated by Django 4.2.20 on 2025-04-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_venue_db_owner_alter_turfusers_db_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue_db',
            name='venue_image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='image'),
        ),
    ]
