# Generated by Django 5.1.7 on 2025-03-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0002_books_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100, null=True)),
                ('book_author', models.CharField(max_length=100, null=True)),
                ('about_book', models.TextField(null=True)),
                ('book_price', models.IntegerField(default=0)),
                ('book_image', models.ImageField(null=True, upload_to='')),
                ('availability', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
