# Generated by Django 5.1.7 on 2025-03-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0003_book_delete_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_no', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
