# Generated by Django 5.1.7 on 2025-03-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0004_customer_alter_book_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
