# Generated by Django 5.1.7 on 2025-03-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0005_alter_customer_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
