# Generated by Django 5.1.7 on 2025-03-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_db',
        ),
    ]
